import './global/globals.css'
import { Roboto, Baloo_2 } from 'next/font/google'

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['400', '700'],
  subsets: ['latin']
});

const baloo2 = Baloo_2({
  variable: '--font-baloo2',
  weight: ['700', '800'],
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={
        `${roboto.variable} ${baloo2.variable}
        h-screen
      `}>
        {children}
      </body>
    </html>
  )
}
